name: flutter_google_maps_example
description: Demonstrates how to use the flutter_google_maps package.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_google_maps:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/map-marker-warehouse.png
