name: flutter_google_maps
version: 5.0.1
homepage: https://github.com/marchdev-tk/flutter_google_maps
description: A Flutter plugin for integrating Google Maps in iOS, Android and Web applications. It is a wrapper of google_maps_flutter for Mobile and google_maps for Web.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^3.1.0
  google_maps_flutter: ^2.0.8
  google_directions_api: ^0.9.0
  google_maps: ^5.3.0
  http: ^0.13.3
  flinq: ^2.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png