name: flutter_google_maps
version: 3.4.0
homepage: https://github.com/marchdev-tk/flutter_google_maps
description: A Flutter plugin for integrating Google Maps in iOS, Android and Web applications. It is a wrapper of google_maps_flutter for Mobile and google_maps for Web.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^2.0.0
  google_maps_flutter: ^0.5.24+1
  google_directions_api: ^0.5.0
  google_maps: ^3.4.1
  http: ^0.12.0+4
  flinq: ^1.1.0
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png