name: flutter_google_maps
version: 4.0.1
homepage: https://github.com/taskhunt/flutter_google_maps
description: A Flutter plugin for integrating Google Maps in iOS, Android and Web applications. It is a wrapper of google_maps_flutter for Mobile and google_maps for Web.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^3.1.0
  google_maps_flutter: ^0.5.28+1
  google_directions_api: ^0.9.0
  google_maps: ^3.4.3
  http: ^0.13.3
  flinq: ^2.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png